# Generated by Django 3.2.4 on 2021-07-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('shape_file', models.FileField(upload_to='city/shape_files')),
                ('crime_data', models.FileField(upload_to='city/crime_data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
