beat_name = 'beat_name'
input_shapefile_path = 'input_shapefile_path'
output_features = 'output_features'
zone_creation_method = 'zone_creation_method'
number_of_zones = 'number_of_zones'
zone_building_criteria_target = 'zone_building_criteria_target'
zone_building_criteria = 'zone_building_criteria'
spatial_constraints = 'spatial_constraints'
