# Generated by Django 3.2.4 on 2021-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city_shapefile', models.FileField(upload_to='city_shapefiles/')),
                ('beats_img', models.ImageField(upload_to='city_beats/')),
                ('cfs_chart_img', models.ImageField(upload_to='city_cfs_chart/')),
                ('crime_data', models.FileField(upload_to='city_crime_ds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
