# Generated by Django 3.2.4 on 2021-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='beats_shapefile',
            field=models.FileField(blank=True, null=True, upload_to='beat_shapefiles/'),
        ),
    ]
