# Generated by Django 3.2.4 on 2021-09-25 06:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='disposition',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1 - Field Interview'), (2, '2 - False Alarm'), (3, '3 - Unable to locate'), (5, '5 - Assist Fire Department'), (6, '6 - Report'), (9, '9 - Contact made')], max_length=11),
        ),
    ]
