# Generated by Django 3.2.4 on 2021-09-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_alter_crime_disposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=100)),
                ('disposition', models.CharField(max_length=100)),
                ('beat_creation_method', models.CharField(max_length=100)),
                ('cfs_per_beat', models.IntegerField(blank=True, null=True)),
                ('number_of_beats', models.IntegerField(blank=True, null=True)),
                ('start_datetime', models.CharField(max_length=100)),
                ('end_datetime', models.CharField(max_length=100)),
                ('is_incident', models.BooleanField()),
            ],
        ),
    ]
