# Generated by Django 3.2.4 on 2021-09-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0002_auto_20210913_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='city_shapefile',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='polygon_wise_count_shapefile',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterField(
            model_name='city',
            name='crime_data',
            field=models.FileField(blank=True, null=True, upload_to='city_crime_ds/'),
        ),
    ]
