# Generated by Django 3.2.4 on 2021-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='beat_shapefile_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
