# Generated by Django 3.2.4 on 2021-09-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0004_query_beat_shapefile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='beats_shapefile',
        ),
        migrations.RemoveField(
            model_name='city',
            name='polygon_wise_count_shapefile',
        ),
    ]
