# Generated by Django 3.2.4 on 2021-10-07 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_auto_20210930_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='priority',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
