# Generated by Django 3.2.4 on 2021-10-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0007_alter_crime_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_shapefile',
            field=models.FileField(blank=True, null=True, upload_to='city_shapefiles/'),
        ),
    ]
