# Generated by Django 3.2.4 on 2021-10-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0008_alter_city_city_shapefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
