# Generated by Django 3.2.4 on 2021-10-16 06:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0010_alter_crime_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='priority',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (9, 9)], max_length=15),
        ),
    ]
