# Generated by Django 3.2.4 on 2021-10-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0011_alter_crime_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='lon',
        ),
    ]
