# Generated by Django 3.2.4 on 2021-10-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0012_auto_20211015_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='event_number',
        ),
    ]
