# Generated by Django 3.2.4 on 2021-10-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0013_remove_crime_event_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='address',
            field=models.CharField(max_length=512),
        ),
    ]
